version: 2

jobs:
  test:
    docker:
      - image: circleci/node:13.0.1
    working_directory: ~/repo
    steps:
      - checkout
      - run: 
          name: npm install
          command: npm install
      - run: 
          name: Run test
          command: npm test

workflows:
  version: 2
  workflows:
    jobs:
      - test
